# file: .github/workflows/staging.yaml
on:
  push:
    paths-ignore:
      - '*.md'
      - 'LICENSE'

jobs:
  update-shared-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Set Okteto Context
      uses: okteto/context@6a635bdbc7aef8c3af516714dadc4ca842aa3b22
      with:
        url: https://ramiro.okteto.dev
        token: ${{ secrets.OKTETO_TOKEN }}
        
    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: shared

    - name: Deploy or update environment
      uses: okteto/pipeline@latest
      with:
        namespace: shared
        timeout: 15m
